package PhoneNetworkApp;

import java.io.*;
import GraphFramework.*;
import java.util.Scanner;

public class PhoneNWDesignApp {

    public static void main(String[] args) throws FileNotFoundException, IOException{
        // Scanner object to read data from input file
        Scanner input = new Scanner(System.in);
        int reqNumber = 0;
        
        while(reqNumber != 3) {
            // Header of the program
            System.out.println("\n-----------------------------Phone NetWork Design App-----------------------------");
            System.out.println("    Compute minimum spanning tree using Kruskal & Min-heap based Prim algorithm   ");
            System.out.println("----------------------------------------------------------------------------------");
            System.out.println("Requirement 1. Use readGraphFromFile function");
            System.out.println("Requirement 2. Use makeGraph function");
            System.out.println("Requirement 3. Exit");
        
            // user will choose a requirement number and then read the number and save it in a variable
            System.out.print("\nPlease choose the function you want to use (enter 1, 2 , or 3 only) : ");
            reqNumber = input.nextInt();
            
            // a while loop to make sure that the user entered a valid number
            while(reqNumber != 1 && reqNumber != 2 && reqNumber != 3){
                System.out.println("Invalid number. Please Try Again.");
                System.out.print("\nPlease choose the function you want to use (enter 1, 2 , or 3 only) : ");
                reqNumber = input.nextInt();
            }
            
            // create mst algorithm object (used for both methods and for both MHPrim and Kruskal)
            MSTAlgorithm mstAlgorithm;
            
            // requirement 1: ---> using method readGraphFromFile
            if(reqNumber == 1){
                System.out.println("\n-----------------Requirement 1. readGraphFromFile-----------------");
                // input file to read data from it
                File inputFile = new File("input.txt");

                // Check if the input file does exist
                if(!inputFile.exists()){
                    System.out.println("The input file does not exist."); // print a message
                    System.exit(0); // exit the program
                }
                
                //BluePrintsGraph object 
                BluePrintsGraph graph1 = new BluePrintsGraph();
                graph1.readGraphFromFile(inputFile); // call readGraphFromFile
                
                // Kruskal Algorithm
                    mstAlgorithm = new KruskalAlg(graph1); // initialize to kruskal
                    mstAlgorithm.constructMST(graph1); // call method to construct MST
                    // print output
                    System.out.println("\nThe phone network (minimum spanning tree) generated by Kruskal algorithm is as follows:");
                    mstAlgorithm.displayResultingMST(); // call method to display MST result 
                    mstAlgorithm.displayMSTcost(); // call method to calculate total cost
                //
                
                // Min-Heap Prim Algorithm
                    mstAlgorithm = new MHPrimAlg(graph1); // initialize to MHPrim
                    mstAlgorithm.constructMST(graph1); // call method to construct MST
                    // print output
                    System.out.println("\nThe phone network (minimum spanning tree) generated by min-heap based Prim algorithm\n" +
                                    "is as follows:");
                    mstAlgorithm.displayResultingMST(); // call method to diplay MST result 
                    mstAlgorithm.displayMSTcost(); // call method to calculate total cost
                //

            }
            
            // create vertexNum and edgeNum to save data
            int vertexNum = 0;
            int edgeNum = 0;
            
            // requirement 2: ---> using makeGraph method
            if(reqNumber == 2){ // print the following
                System.out.println("\n---------------------Requirement 2. makeGraph---------------------");
                System.out.println("The possible cases for vertices(n) and edges(m): ");
                System.out.println("\nFirst Graph:   n=1000, m=10000\nSecond Graph:  n=1000, m=15000"
                                + "\nThird Graph:   n=1000, m=25000");
                System.out.println("Fourth Graph:  n=5000, m=15000\nFifth Graph:   n=5000, m=25000");
                System.out.println("Sixth Graph:   n=10000, m=15000\nSeventh Graph: n=10000, m=25000\n");
                System.out.print("Please choose a valid graph number (from 1 to 7): ");
                
                // the user will choose case number and it will be saved here
                int graphNum = input.nextInt();
                
                // while loop to ensure that the user has entered a valid number 
                // if not, enter while loop and ask user to enter it again until the user enters a valid number
                while(1 > graphNum || graphNum > 7){
                    System.out.println("Invalid Graph Number. Please Try Again.");
                    System.out.print("\nPlease choose a valid graph number (from 1 to 7): ");
                    graphNum = input.nextInt();
                }
                
                // switch statement for graph cases
                switch (graphNum) {
                    case 1: // First Graph:   n=1000, m=10000
                        vertexNum = 1000;
                        edgeNum = 10000;
                        break;
                    case 2: // Second Graph:  n=1000, m=15000
                        vertexNum = 1000;
                        edgeNum = 15000;
                        break;
                    case 3: // Third Graph:   n=1000, m=25000
                        vertexNum = 1000;
                        edgeNum = 25000;
                        break;
                    case 4: // Fourth Graph:  n=5000, m=15000
                        vertexNum = 5000;
                        edgeNum = 15000;
                        break;
                    case 5: // Fifth Graph:   n=5000, m=25000 
                        vertexNum = 5000;
                        edgeNum = 25000;
                        break;
                    case 6: // Sixth Graph:   n=10000, m=15000
                        vertexNum = 10000;
                        edgeNum = 15000;
                        break;
                    case 7: // Seventh Graph: n=10000, m=25000
                        vertexNum = 10000;
                        edgeNum = 25000;
                        break;
                }
                
                //BluePrintsGraph object 
                BluePrintsGraph graph2 = new BluePrintsGraph(vertexNum, edgeNum, false); // false means undirected graph
                graph2.makeGraph(vertexNum, edgeNum); // call makeGraph method
                
                // Kruskal Algorithm
                    // print output
                    System.out.println("\nThe phone network (minimum spanning tree) generated by Kruskal Algorithm");
                    mstAlgorithm = new KruskalAlg(graph2); // initialize to kruskal
                    double startTime = System.currentTimeMillis(); // a variable to record starting time of the algoritnm
                    mstAlgorithm.constructMST(graph2); // call method to construct MST
                    double finishtTime = System.currentTimeMillis(); // a variable to record finishing time of the algoritnm
                    double totalTime = finishtTime - startTime; // calculate total time by subtracting startTime from finishTime
                    mstAlgorithm.displayMSTcost(); // call method to calculate cost
                    System.out.println("The running time of the Kruskal Algorithm is " + totalTime + " ms"); // print time
                //

                // Min-Heap Prim Algorithm
                    // print output
                    System.out.println("\nThe phone network (minimum spanning tree) generated by Min-Heap based Prim Algorithm");
                    mstAlgorithm = new MHPrimAlg(graph2); // initialize to MHPrim
                    startTime = System.currentTimeMillis(); // a variable to record starting time of the algoritnm
                    mstAlgorithm.constructMST(graph2); // call method to construct MST
                    finishtTime = System.currentTimeMillis(); // a variable to record finishing time of the algoritnm
                    totalTime = finishtTime - startTime; // calculate total time by subtracting startTime from finishTime
                    mstAlgorithm.displayMSTcost(); // call method to calculate cost
                    
                    System.out.println("The running time of the Min-Heap based Prim Algorithm is " + totalTime + " ms"); // print time
                //
            }   
        }
        System.out.println("\nThank you for using Phone NetWork Desing App, Good Bye!\n"); // ending message
        input.close(); // close input file
    }
    
}
